#!/usr/bin/env python3
"""
DOJ Epstein Library — Full Download Manager
=============================================
Downloads all files from the manifest generated by the browser-based extractor.
Supports resuming, parallel downloads, progress tracking, and integrity checks.

Usage:
  # Download everything (resumes automatically)
  python3 download_full_library.py

  # Download specific section only
  python3 download_full_library.py --section DataSet_01

  # Dry run - show what would be downloaded
  python3 download_full_library.py --dry-run

  # Set custom destination
  python3 download_full_library.py --dest-dir /path/to/storage

  # Adjust concurrency and delay
  python3 download_full_library.py --workers 3 --delay 0.5

Options:
  --manifest FILE    Path to manifest JSON (default: ./_pipeline_output/doj_full_manifest.json)
  --dest-dir DIR     Destination directory (default: ./doj_full_library)
  --section NAME     Only download this section
  --dry-run          Show stats without downloading
  --workers N        Concurrent download threads (default: 2, max 4)
  --delay N          Seconds between downloads per worker (default: 0.5)
  --resume           Skip files that already exist (default: True)
  --no-resume        Re-download all files even if they exist
  --max-retries N    Max retries per file (default: 3)
  --report           Generate download report after completion
"""

import argparse
import json
import os
import sys
import time
import hashlib
import threading
from pathlib import Path
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urlparse, unquote

try:
    import requests
except ImportError:
    print("Installing requests...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install",
                          "requests", "--break-system-packages", "-q"])
    import requests

# ═══════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Accept": "application/pdf,application/octet-stream,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Referer": "https://www.justice.gov/epstein/doj-disclosures",
    # Age verification cookie — justice.gov requires this to serve PDFs
    # Without it, all requests redirect to /age-verify and return HTML
    "Cookie": "justiceGovAgeVerified=true",
}

# Files smaller than this are likely age-gate HTML pages, not real PDFs
MIN_PDF_SIZE = 1024  # 1KB — real PDFs are much larger than the 54KB HTML page
AGE_GATE_SIZE = 53571  # Exact size of the age-gate HTML redirect page

# ═══════════════════════════════════════════
# PROGRESS TRACKER
# ═══════════════════════════════════════════

class ProgressTracker:
    def __init__(self, total_files, total_sections):
        self.lock = threading.Lock()
        self.total = total_files
        self.downloaded = 0
        self.skipped = 0
        self.failed = 0
        self.total_bytes = 0
        self.section_counts = defaultdict(lambda: {"downloaded": 0, "skipped": 0, "failed": 0})
        self.start_time = time.time()
        self.current_section = ""
        self.failed_files = []

    def update(self, section, status, size_bytes=0, filename="", error=""):
        with self.lock:
            if status == "downloaded":
                self.downloaded += 1
                self.total_bytes += size_bytes
            elif status == "skipped":
                self.skipped += 1
            elif status == "failed":
                self.failed += 1
                self.failed_files.append({"section": section, "filename": filename, "error": error})

            self.section_counts[section][status] += 1
            done = self.downloaded + self.skipped + self.failed
            elapsed = time.time() - self.start_time
            rate = self.downloaded / elapsed if elapsed > 0 else 0
            eta = (self.total - done) / rate / 60 if rate > 0 else 0
            mb = self.total_bytes / (1024 * 1024)

            if done % 10 == 0 or status == "failed":
                print(f"\r  [{done}/{self.total}] "
                      f"✓{self.downloaded} ⊘{self.skipped} ✗{self.failed} | "
                      f"{mb:.0f}MB | {rate:.1f}/s | ETA {eta:.0f}min  ",
                      end="", flush=True)

    def report(self):
        elapsed = (time.time() - self.start_time) / 60
        mb = self.total_bytes / (1024 * 1024)
        gb = mb / 1024

        print(f"\n\n{'='*60}")
        print(f"  DOWNLOAD COMPLETE")
        print(f"{'='*60}")
        print(f"  Downloaded: {self.downloaded}")
        print(f"  Skipped:    {self.skipped}")
        print(f"  Failed:     {self.failed}")
        print(f"  Total size: {gb:.2f} GB ({mb:.0f} MB)")
        print(f"  Duration:   {elapsed:.1f} minutes")
        print(f"{'='*60}")

        if self.failed_files:
            print(f"\n  Failed files ({len(self.failed_files)}):")
            for f in self.failed_files[:20]:
                print(f"    [{f['section']}] {f['filename']}: {f['error']}")
            if len(self.failed_files) > 20:
                print(f"    ... and {len(self.failed_files) - 20} more")

        return {
            "downloaded": self.downloaded,
            "skipped": self.skipped,
            "failed": self.failed,
            "total_bytes": self.total_bytes,
            "duration_minutes": round(elapsed, 1),
            "failed_files": self.failed_files,
            "section_counts": dict(self.section_counts),
        }


# ═══════════════════════════════════════════
# DOWNLOADER
# ═══════════════════════════════════════════

def download_file(session, file_info, dest_dir, resume, max_retries, delay, tracker):
    """Download a single file with retry logic."""
    section = file_info.get("section", "unknown")
    url = file_info["url"]
    filename = file_info.get("filename", "")

    if not filename:
        filename = unquote(urlparse(url).path.split("/")[-1])
    if not filename:
        filename = hashlib.md5(url.encode()).hexdigest() + ".pdf"

    # Clean filename
    filename = filename.replace("%20", " ").replace("?", "_").replace("&", "_")

    section_dir = Path(dest_dir) / section
    section_dir.mkdir(parents=True, exist_ok=True)
    filepath = section_dir / filename

    # Resume check — skip if file exists AND is a real PDF (not an age-gate HTML page)
    if resume and filepath.exists():
        existing_size = filepath.stat().st_size
        if existing_size > MIN_PDF_SIZE and existing_size != AGE_GATE_SIZE:
            # Check first bytes for PDF magic number (%PDF)
            try:
                with open(filepath, "rb") as check_f:
                    header = check_f.read(5)
                if header == b"%PDF-":
                    tracker.update(section, "skipped")
                    return
            except:
                pass
            # If not a valid PDF, re-download it

    for attempt in range(max_retries):
        try:
            resp = session.get(url, timeout=60, stream=True)

            if resp.status_code == 200:
                with open(filepath, "wb") as f:
                    for chunk in resp.iter_content(chunk_size=16384):
                        f.write(chunk)

                size = filepath.stat().st_size
                if size > 0:
                    # Validate it's actually a PDF, not an age-gate HTML page
                    with open(filepath, "rb") as check_f:
                        header = check_f.read(5)
                    if header != b"%PDF-":
                        # Got HTML instead of PDF — age gate may still be blocking
                        if attempt < max_retries - 1:
                            filepath.unlink(missing_ok=True)
                            time.sleep(2)
                            continue
                        tracker.update(section, "failed", filename=filename,
                                       error="Got HTML instead of PDF (age-gate?)")
                        filepath.unlink(missing_ok=True)
                        return
                    tracker.update(section, "downloaded", size_bytes=size)
                    time.sleep(delay)
                    return
                else:
                    filepath.unlink(missing_ok=True)
                    continue

            elif resp.status_code == 429:
                # Rate limited — back off
                wait = min(30, 5 * (attempt + 1))
                time.sleep(wait)
                continue

            elif resp.status_code == 403:
                # Try once more with fresh session headers
                if attempt == 0:
                    time.sleep(2)
                    continue
                tracker.update(section, "failed", filename=filename, error=f"HTTP {resp.status_code}")
                return

            else:
                if attempt < max_retries - 1:
                    time.sleep(2)
                    continue
                tracker.update(section, "failed", filename=filename, error=f"HTTP {resp.status_code}")
                return

        except requests.exceptions.Timeout:
            if attempt < max_retries - 1:
                time.sleep(3)
                continue
            tracker.update(section, "failed", filename=filename, error="Timeout")
            return

        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(2)
                continue
            tracker.update(section, "failed", filename=filename, error=str(e)[:100])
            return


def download_section(manifest_section, section_name, dest_dir, resume, max_retries, delay, workers, tracker):
    """Download all files in a section."""
    files = manifest_section
    print(f"\n  {section_name}: {len(files)} files")

    session = requests.Session()
    session.headers.update(HEADERS)
    # Ensure cookie is set at session level too
    session.cookies.set("justiceGovAgeVerified", "true", domain=".justice.gov", path="/")

    if workers <= 1:
        for f in files:
            download_file(session, f, dest_dir, resume, max_retries, delay, tracker)
    else:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = []
            for f in files:
                futures.append(pool.submit(
                    download_file, session, f, dest_dir, resume, max_retries, delay, tracker
                ))
            for future in as_completed(futures):
                try:
                    future.result()
                except Exception as e:
                    pass


# ═══════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="DOJ Epstein Library Full Downloader")
    parser.add_argument("--manifest", default="./_pipeline_output/doj_full_manifest.json")
    parser.add_argument("--dest-dir", default="./doj_full_library")
    parser.add_argument("--section", help="Download only this section")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--workers", type=int, default=2, help="Concurrent downloads (max 4)")
    parser.add_argument("--delay", type=float, default=0.5, help="Delay between downloads")
    parser.add_argument("--no-resume", action="store_true", help="Re-download all files")
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--report", action="store_true")
    args = parser.parse_args()

    args.workers = min(args.workers, 4)
    resume = not args.no_resume

    # Load manifest
    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"ERROR: Manifest not found at {manifest_path}")
        print("Run the browser extractor first, then save the manifest.")
        sys.exit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    # Filter section if specified
    if args.section:
        if args.section not in manifest:
            print(f"ERROR: Section '{args.section}' not found. Available: {list(manifest.keys())}")
            sys.exit(1)
        manifest = {args.section: manifest[args.section]}

    # Stats
    total_files = sum(len(files) for files in manifest.values())
    total_sections = len(manifest)

    print(f"\n{'='*60}")
    print(f"  DOJ EPSTEIN LIBRARY DOWNLOADER")
    print(f"{'='*60}")
    print(f"  Manifest:    {manifest_path}")
    print(f"  Destination: {args.dest_dir}")
    print(f"  Sections:    {total_sections}")
    print(f"  Total files: {total_files:,}")
    print(f"  Workers:     {args.workers}")
    print(f"  Delay:       {args.delay}s")
    print(f"  Resume:      {resume}")
    print(f"{'='*60}")

    if args.dry_run:
        print("\n  DRY RUN — File counts by section:")
        for section, files in sorted(manifest.items()):
            exts = defaultdict(int)
            for f in files:
                ext = f.get("filename", "").rsplit(".", 1)[-1].lower() if "." in f.get("filename", "") else "unknown"
                exts[ext] += 1
            ext_str = ", ".join(f"{v} .{k}" for k, v in sorted(exts.items(), key=lambda x: -x[1]))
            print(f"    {section}: {len(files)} files ({ext_str})")

        # Estimate size (rough: avg 1MB per PDF)
        est_gb = total_files * 1.0 / 1024
        print(f"\n  Estimated total size: ~{est_gb:.0f} GB (assuming ~1MB avg per file)")
        print(f"  Estimated time: ~{total_files * args.delay / 3600:.1f} hours at {args.delay}s delay")
        return

    # Download
    dest = Path(args.dest_dir)
    dest.mkdir(parents=True, exist_ok=True)

    tracker = ProgressTracker(total_files, total_sections)

    # Process sections in order (smaller first for quick wins)
    section_order = sorted(manifest.keys(), key=lambda s: len(manifest[s]))

    for section_name in section_order:
        download_section(
            manifest[section_name], section_name, args.dest_dir,
            resume, args.max_retries, args.delay, args.workers, tracker
        )

    result = tracker.report()

    # Save report
    if args.report or True:  # Always save report
        report_path = Path(args.dest_dir) / "_download_report.json"
        with open(report_path, "w") as f:
            json.dump(result, f, indent=2, default=str)
        print(f"\n  Report saved to {report_path}")

    # Save failed files for retry
    if result["failed_files"]:
        retry_path = Path(args.dest_dir) / "_retry_manifest.json"
        retry_manifest = defaultdict(list)
        for f in result["failed_files"]:
            # Find original file info from manifest
            for sec_files in manifest.values():
                for fi in sec_files:
                    if fi.get("filename") == f["filename"]:
                        retry_manifest[f["section"]].append(fi)
                        break
        with open(retry_path, "w") as f_out:
            json.dump(dict(retry_manifest), f_out, indent=2)
        print(f"  Retry manifest saved to {retry_path}")
        print(f"  To retry: python3 {sys.argv[0]} --manifest {retry_path}")


if __name__ == "__main__":
    main()
